nmap <F5>  :call vimspector#Continue()<CR>
nmap <F3>  :call vimspector#Reset()<CR>
nmap <F4>  :call vimspector#Restart()<CR>
nmap <F6>  :call vimspector#Pause()<CR>
nmap <F9>  :call vimspector#ToggleBreakpoint()<CR>
nmap <F8>  :call vimspector#GoToCurrentLine()<CR>
nmap <F10> :call vimspector#StepOver()<CR>
nmap <F11> :call vimspector#StepInto()<CR>
nmap <F12> :call vimspector#StepOut()<CR>
